export const SUPPORTED_BORROWING_POOLS = {
  cadc: {
    id: 'cadc',
    name: 'CADC',
    logo: '/assets/stablecoins/cadc.png',
    logoCountry: '/assets/flags/flag-ca.png',
    networks: [
      {
        id: 'base',
        name: 'Base',
        logo: '/assets/network/base.png',
        chainId: 8453,
        address: '0xca03A4dFE09f664890ee7B46D9Af4F0B6d5f6f15',
        decimals: 18,
        isActive: true,
      },
      {
        id: 'arbitrum',
        name: 'Arbitrum',
        logo: '/assets/network/arbitrum.png',
        chainId: 42161,
        address: '0x99d19F4Cb938E0aAD646358c20cB9D0CE0A7a945',
        decimals: 18,
        isActive: true,
      },
    ],
  },
  cngn: {
    id: 'cngn',
    name: 'CNGN',
    logo: '/assets/stablecoins/cngn.png',
    logoCountry: '/assets/flags/flag-ng.png',
    networks: [
      {
        id: 'base',
        name: 'Base',
        logo: '/assets/network/base.png',
        chainId: 8453,
        address: '0xED6Cfb1D2F61F75419BaB537Ca1C5351B6a4c017',
        decimals: 6,
        isActive: true,
      },
      {
        id: 'arbitrum',
        name: 'Arbitrum',
        logo: '/assets/network/arbitrum.png',
        chainId: 42161,
        address: '0xA0F8C84E78eabDF241A9fA9Ff6733AB17bB4E7FA',
        decimals: 6,
        isActive: true,
      },
    ],
  },
  krwt: {
    id: 'krwt',
    name: 'KRWT',
    logo: '/assets/stablecoins/krwt.png',
    logoCountry: '/assets/flags/flag-kr.png',
    networks: [
      {
        id: 'base',
        name: 'Base',
        logo: '/assets/network/base.png',
        chainId: 8453,
        address: '0xD773084B8Cd424AD87D35bE6901255feE285A763',
        decimals: 18,
        isActive: true,
      },
      {
        id: 'arbitrum',
        name: 'Arbitrum',
        logo: '/assets/network/arbitrum.png',
        chainId: 42161,
        address: '0x0B214413CAc3E0B8F356181d7339626FCafff6Bd',
        decimals: 18,
        isActive: true,
      },
    ],
  },
  tryb: {
    id: 'tryb',
    name: 'TRYB',
    logo: '/assets/stablecoins/tryb.png',
    logoCountry: '/assets/flags/flag-tr.png',
    networks: [
      {
        id: 'base',
        name: 'Base',
        logo: '/assets/network/base.png',
        chainId: 8453,
        address: '0x1D7c9083d76aD235aE44d90Bc13EcA74Ccc2Ed42',
        decimals: 6,
        isActive: true,
      },
      {
        id: 'arbitrum',
        name: 'Arbitrum',
        logo: '/assets/network/arbitrum.png',
        chainId: 42161,
        address: '0xa7f56bc3252c676E43Ff1F3e6780Dbbc7679D7a6',
        decimals: 6,
        isActive: true,
      },
    ],
  },
  mxne: {
    id: 'mxne',
    name: 'MXNE',
    logo: '/assets/stablecoins/mxne.png',
    logoCountry: '/assets/flags/flag-mx.png',
    networks: [
      {
        id: 'base',
        name: 'Base',
        logo: '/assets/network/base.png',
        chainId: 8453,
        address: '0xB7e6d4119F5E482D8d68D0AA4c81F14A082Ec917',
        decimals: 6,
        isActive: true,
      },
      {
        id: 'arbitrum',
        name: 'Arbitrum',
        logo: '/assets/network/arbitrum.png',
        chainId: 42161,
        address: '0x14954b6a207A4CC908f44354e61997070507fCC4',
        decimals: 6,
        isActive: true,
      },
    ],
  },
  xsgd: {
    id: 'xsgd',
    name: 'XSGD',
    logo: '/assets/stablecoins/xsgd.png',
    logoCountry: '/assets/flags/flag-sg.png',
    networks: [
      {
        id: 'base',
        name: 'Base',
        logo: '/assets/network/base.png',
        chainId: 8453,
        address: '0xef49434AcC92ED24e7d245f748aacDE471A68F06',
        decimals: 6,
        isActive: true,
      },
      {
        id: 'arbitrum',
        name: 'Arbitrum',
        logo: '/assets/network/arbitrum.png',
        chainId: 42161,
        address: '0x1aA55163E448b100ac4541C69cf2b55C909A2bE9',
        decimals: 6,
        isActive: true,
      },
    ],
  },
  zarp: {
    id: 'zarp',
    name: 'ZARP',
    logo: '/assets/stablecoins/zarp.png',
    logoCountry: '/assets/flags/flag-za.png',
    networks: [
      {
        id: 'base',
        name: 'Base',
        logo: '/assets/network/base.png',
        chainId: 8453,
        address: '0x5F01296847f20Fc68C79D051AB75Fb9169096F00',
        decimals: 18,
        isActive: true,
      },
      {
        id: 'arbitrum',
        name: 'Arbitrum',
        logo: '/assets/network/arbitrum.png',
        chainId: 42161,
        address: '0x623Cf9E33F269Fd459467E98a5e12Db4C2FBCAe0',
        decimals: 18,
        isActive: true,
      },
    ],
  },
  idrx: {
    id: 'idrx',
    name: 'IDRX',
    logo: '/assets/stablecoins/idrx.png',
    logoCountry: '/assets/flags/flag-id.png',
    networks: [
      {
        id: 'base',
        name: 'Base',
        logo: '/assets/network/base.png',
        chainId: 8453,
        address: '0x74Ae55CA4EaA2337f309F77A7AF1b60Ea9085FB6',
        decimals: 2,
        isActive: true,
      },
      {
        id: 'arbitrum',
        name: 'Arbitrum',
        logo: '/assets/network/arbitrum.png',
        chainId: 42161,
        address: '0xB4626C50fb6A0019FEECD442310cd1F7395e2148',
        decimals: 2,
        isActive: true,
      },
    ],
  },
  eurc: {
    id: 'eurc',
    name: 'EURC',
    logo: '/assets/stablecoins/eurc.png',
    logoCountry: '/assets/flags/flag-eu.png',
    networks: [
      {
        id: 'base',
        name: 'Base',
        logo: '/assets/network/base.png',
        chainId: 8453,
        address: '0xB2B60Bb1e9796cAE4Dc4c87f456db675871b0d2B',
        decimals: 6,
        isActive: true,
      },
      {
        id: 'arbitrum',
        name: 'Arbitrum',
        logo: '/assets/network/arbitrum.png',
        chainId: 42161,
        address: '0x8d55C23664B46212bC6dC03d03E237988c0d3646',
        decimals: 6,
        isActive: true,
      },
    ],
  },
};

export const SUPPORTED_COLLATERAL = {
  bIB01: {
    id: 'bIB01',
    name: 'bIB01',
    logo: '/assets/rwa/bIB01.png',
    logoCountry: '',
    networks: [
      {
        id: 'base',
        name: 'Base',
        logo: '/assets/network/base.png',
        chainId: 8453,
        address: '0x650776773016488249D90f5CE25bC2f87Bd037e4',
        decimals: 18,
        isActive: true,
      },
    ],
  },
  bCOIN: {
    id: 'bCOIN',
    name: 'bCOIN',
    logo: '/assets/rwa/bCOIN.png',
    logoCountry: '',
    networks: [
      {
        id: 'base',
        name: 'Base',
        logo: '/assets/network/base.png',
        chainId: 8453,
        address: '0x776E57A6411F734368360BA1c717F5d806CaE7a9',
        decimals: 18,
        isActive: true,
      },
    ],
  },
  bCSPX: {
    id: 'bCSPX',
    name: 'bCSPX',
    logo: '/assets/rwa/bCSPX.png',
    logoCountry: '',
    networks: [
      {
        id: 'base',
        name: 'Base',
        logo: '/assets/network/base.png',
        chainId: 8453,
        address: '0x18178895c9Fb3b7a5f69295826d8F18Cc3B79453',
        decimals: 18,
        isActive: true,
      },
    ],
  },
  bIBTA: {
    id: 'bIBTA',
    name: 'bIBTA',
    logo: '/assets/rwa/bIBTA.png',
    logoCountry: '',
    networks: [
      {
        id: 'base',
        name: 'Base',
        logo: '/assets/network/base.png',
        chainId: 8453,
        address: '0xBBA0Ba72349226ba2887583cD7078480B2f02c12',
        decimals: 18,
        isActive: true,
      },
    ],
  },
  bHIGH: {
    id: 'bHIGH',
    name: 'bHIGH',
    logo: '/assets/rwa/bHIGH.png',
    logoCountry: '',
    networks: [
      {
        id: 'base',
        name: 'Base',
        logo: '/assets/network/base.png',
        chainId: 8453,
        address: '0xf15bA231663f5351F3069C6C72fB117238D66047',
        decimals: 18,
        isActive: true,
      },
    ],
  },
  bTSLA: {
    id: 'bTSLA',
    name: 'bTSLA',
    logo: '/assets/rwa/bTSLA.png',
    logoCountry: '',
    networks: [
      {
        id: 'base',
        name: 'Base',
        logo: '/assets/network/base.png',
        chainId: 8453,
        address: '0x2D85b61280CfaCb67ca97c874AeeF44Aab16Ba63',
        decimals: 18,
        isActive: true,
      },
    ],
  },
  bGOOGL: {
    id: 'bGOOGL',
    name: 'bGOOGL',
    logo: '/assets/rwa/bGOOGL.png',
    logoCountry: '',
    networks: [
      {
        id: 'base',
        name: 'Base',
        logo: '/assets/network/base.png',
        chainId: 8453,
        address: '0xdb21725DB0162bf173F41CEBFd5dd5a023b56363',
        decimals: 18,
        isActive: true,
      },
    ],
  },
  bNVDA: {
    id: 'bNVDA',
    name: 'bNVDA',
    logo: '/assets/rwa/bNVDA.png',
    logoCountry: '',
    networks: [
      {
        id: 'base',
        name: 'Base',
        logo: '/assets/network/base.png',
        chainId: 8453,
        address: '0xaCc509f29746DE5ADf75007aBeb84aF3e101dDD7',
        decimals: 18,
        isActive: true,
      },
    ],
  },
  bMSFT: {
    id: 'bMSFT',
    name: 'bMSFT',
    logo: '/assets/rwa/bMSFT.png',
    logoCountry: '',
    networks: [
      {
        id: 'base',
        name: 'Base',
        logo: '/assets/network/base.png',
        chainId: 8453,
        address: '0xAB0903D4BB2a7ecEB4cA88d74F3924c3fE0A8DC1',
        decimals: 18,
        isActive: true,
      },
    ],
  },
  bGME: {
    id: 'bGME',
    name: 'bGME',
    logo: '/assets/rwa/bGME.png',
    logoCountry: '',
    networks: [
      {
        id: 'base',
        name: 'Base',
        logo: '/assets/network/base.png',
        chainId: 8453,
        address: '0x09490E9e625adc21DB63183e9BF43eD3F8630782',
        decimals: 18,
        isActive: true,
      },
    ],
  },
  bZPR1: {
    id: 'bZPR1',
    name: 'bZPR1',
    logo: '/assets/rwa/bZPR1.png',
    logoCountry: '',
    networks: [
      {
        id: 'base',
        name: 'Base',
        logo: '/assets/network/base.png',
        chainId: 8453,
        address: '0xc79b05e2962C1d3d9f5FEFE7c5bde9097629989b',
        decimals: 18,
        isActive: true,
      },
    ],
  },
};
