export const LOCAL_STABLECOIN_OPTIONS = [
  {
    id: 'idrx',
    name: 'IDRX',
    lltv: '80%',
    apr: '0.03%',
    icon: '/assets/stablecoins/idrx.png',
    flag: '/assets/flags/flag-id.png',
  },
  {
    id: 'xidr',
    name: 'XIDR',
    lltv: '80%',
    apr: '0.07%',
    icon: '/assets/stablecoins/xidr.png',
    flag: '/assets/flags/flag-id.png',
  },
  {
    id: 'usdc',
    name: 'USDC',
    lltv: '80%',
    apr: '0.033%',
    icon: '/assets/stablecoins/eurc.png',
    flag: '/assets/flags/flag-us.png',
  },
  {
    id: 'usde',
    name: 'USDe',
    lltv: '80%',
    apr: '0.033%',
    icon: '/assets/stablecoins/usde.png',
    flag: '/assets/flags/flag-us.png',
  },
  {
    id: 'xsgd',
    name: 'XSGD',
    lltv: '80%',
    apr: '0.033%',
    icon: '/assets/stablecoins/xsgd.png',
    flag: '/assets/flags/flag-sg.png',
  },
  {
    id: 'eurc',
    name: 'EURC',
    lltv: '80%',
    apr: '0.033%',
    icon: '/assets/stablecoins/eurc.png',
    flag: '/assets/flags/flag-eu.png',
  },
  {
    id: 'jeur',
    name: 'jEUR',
    lltv: '80%',
    apr: '0.033%',
    icon: '/assets/stablecoins/jeur.png',
    flag: '/assets/flags/flag-eu.png',
  },
];
