export const borrowItems = [
  {
    id: 1,
    imageSrc: '/assets/rwa/bCOIN.png',
    imageAlt: 'bCOIN',
    title: 'bCOIN',
    subtitle: 'Balance 0.00',
    apy: '7.91%',
    apyColor: '#279E73',
  },
  {
    id: 2,
    imageSrc: '/assets/rwa/bCSPX.png',
    imageAlt: 'bCSPX',
    title: 'bCSPX',
    subtitle: 'Balance 0.00',
    apy: '6.45%',
    apyColor: '#279E73',
  },
  {
    id: 3,
    imageSrc: '/assets/rwa/bNVDA.png',
    imageAlt: 'bNVDA',
    title: 'bNVDA',
    subtitle: 'Balance 0.00',
    apy: '5.82%',
    apyColor: '#279E73',
  },
  {
    id: 4,
    imageSrc: '/assets/rwa/bGME.png',
    imageAlt: 'bGME',
    title: 'bGME',
    subtitle: 'Balance 0.00',
    apy: '8.15%',
    apyColor: '#279E73',
  },
  {
    id: 5,
    imageSrc: '/assets/rwa/bGOOGL.png',
    imageAlt: 'bGOOGL',
    title: 'bGOOGL',
    subtitle: 'Balance 0.00',
    apy: '6.78%',
    apyColor: '#279E73',
  },
  {
    id: 6,
    imageSrc: '/assets/rwa/bHIGH.png',
    imageAlt: 'bHIGH',
    title: 'bHIGH',
    subtitle: 'Balance 0.00',
    apy: '7.23%',
    apyColor: '#279E73',
  },
  {
    id: 7,
    imageSrc: '/assets/rwa/bIB01.png',
    imageAlt: 'bIB01',
    title: 'bIB01',
    subtitle: 'Balance 0.00',
    apy: '5.45%',
    apyColor: '#279E73',
  },
  {
    id: 8,
    imageSrc: '/assets/rwa/bIBTA.png',
    imageAlt: 'bIBTA',
    title: 'bIBTA',
    subtitle: 'Balance 0.00',
    apy: '4.92%',
    apyColor: '#279E73',
  },
  {
    id: 9,
    imageSrc: '/assets/rwa/bMSFT.png',
    imageAlt: 'bMSFT',
    title: 'bMSFT',
    subtitle: 'Balance 0.00',
    apy: '6.34%',
    apyColor: '#279E73',
  },
  {
    id: 10,
    imageSrc: '/assets/rwa/bTSLA.png',
    imageAlt: 'bTSLA',
    title: 'bTSLA',
    subtitle: 'Balance 0.00',
    apy: '9.12%',
    apyColor: '#279E73',
  },
  {
    id: 11,
    imageSrc: '/assets/rwa/bZPR1.png',
    imageAlt: 'bZPR1',
    title: 'bZPR1',
    subtitle: 'Balance 0.00',
    apy: '5.67%',
    apyColor: '#279E73',
  },
];
